### ISSUE TITLE
machO chain signature verification not working

### ISSUE THREAD

**Issue by ArtemKar123** [JetBrains/format-ripper#16]
`SignedMessageVerifier.VerifySignatureAsync` fails for machO signed files, when  `verificationParams.BuildChain = true`.

Verification fails with message "ERROR: Build chain for certificate was failed. Issuer=<issuer-info> unable to find valid certification path to requested target" with result of `InvalidChain` instead of expected `Valid`

Relevant test `MachoSignatureVerifierTests.VerifySignWithChainTest` is added in #15.

**Comment by VladRassokhin** [comment]
Underlying error is:
```
java.security.cert.CertPathValidatorException: Unrecognized critical extension(s)
	at java.base/sun.security.provider.certpath.ForwardBuilder.verifyCert(ForwardBuilder.java:765)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.depthFirstSearchForward(SunCertPathBuilder.java:296)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.buildForward(SunCertPathBuilder.java:231)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.buildCertPath(SunCertPathBuilder.java:166)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:134)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at com.jetbrains.signatureverifier.crypt.SignerInfoVerifier.buildCertificateChainAsync(SignerInfoVerifier.kt:200)
	at com.jetbrains.signatureverifier.crypt.SignerInfoVerifier.VerifyAsync(SignerInfoVerifier.kt:83)
	at com.jetbrains.signatureverifier.crypt.SignedMessageVerifier.verifySignatureAsync(SignedMessageVerifier.kt:39)
	at com.jetbrains.signatureverifier.crypt.SignedMessageVerifier.VerifySignatureAsync(SignedMessageVerifier.kt:29)
	at com.jetbrains.signatureverifier.tests.MachoSignatureVerifierTests$VerifySignWithChainTest$1$results$1$1$1.invokeSuspend(MachoSignatureVerifierTests.kt:77)
```

Fix in CustomPkixCertPathChecker: 
```
  override fun getSupportedExtensions(): MutableSet<String> {
    return mutableSetOf(
      OIDs.APPLE_CERTIFICATE_EXTENSION_CODE_SIGNING.id,
      OIDs.APPLE_CERTIFICATE_EXTENSION_KEXT_SIGNING.id
    )
  }
```

**Comment by segrey** [comment]
Any chance to publish a new format-ripper version with the fix to Maven Central?

https://central.sonatype.com/artifact/com.jetbrains.format-ripper/format-ripper/versions (currently, latest is `1.1.1`)

**Comment by ww898** [comment]
@segrey Done
